name: Release
on:
  workflow_dispatch:
  push:
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Get environment variables for later
      - uses: FranzDiebold/github-env-vars-action@v2
      
      - uses: actions/checkout@v4
      - name: Setup Git
        run: |
          git config --global user.email "ryan@nutt.com"
          git config --global user.name "Ryan Nutt"
      - name: Run build
        run: |
          npm install --silent
          npm run build
          git add dist/
          git commit -m "Releasing" --allow-empty
          git push -f origin ${{ env.CI_REF_NAME }}
      - name: Get version
        id: project-version
        uses: "euberdeveloper/ga-project-version@main"
        with:
          package-manager: npm
      - name: Create release
        run: |
          gh release delete ${{ env.CI_REF_NAME }} -y || exit 0
          gh release create ${{ env.CI_REF_NAME }} -t ${{ env.CI_REF_NAME }} -n "Release ${{ env.CI_REF_NAME }}"
        env:
          GH_TOKEN: ${{ github.token }}
      # - name: Tag latest
      #   # Only want to tag latest if this push was to main branch
      #   if: env.CI_REF_NAME == 'main'
      #   run: |
      #     git tag -f latest # Since we are already on main we don't need a ref. This will tag HEAD of main.
      #     git push origin latest --force
      # - name: Release main branch
      #   if: env.CI_REF_NAME == 'main'
      #   id: create_release_main
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: latest
      #     allowUpdates: true
      
      
      # - name: Tag non-main branch
      #   # Branch, but also have to make sure it's not a tag
      #   if: env.CI_REF_NAME != 'main' && startsWith(env.CI_REF, 'refs/heads')
      #   run: |
      #     git tag -f ${{ env.CI_REF_NAME }} # Since we are already on the branch we don't need a ref. This will tag HEAD of the branch.
      #     git push origin tag ${{ env.CI_REF_NAME }} --force
      
      # - name: Release non-main branch
      #   if: env.CI_REF_NAME != 'main'
      #   run: |
      #     gh release delete ${{ env.CI_REF_NAME }} -y
      #     gh release create ${{ env.CI_REF_NAME }} -t ${{ env.CI_REF_NAME }} -n "Release ${{ env.CI_REF_NAME }}"
      #   env:
      #     GH_TOKEN: ${{ github.token }}

